### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by Rafi1018** [LoneWolf4713/auspicious-dots#1]
I installed phyOS hyprland to try your dots out & downloaded all of the resources linked.....
what now ?
Sorry but I'm new to linux
Thanks

**Comment by LoneWolf4713** [comment]
I'm afraid it doesn't work like that, see that's the thing with using other's dotfiles, dotfiles are never meant to drop in and work as they are specially customized for my setup.... you take inspiration from someone's dotfiles and build yours... but if you insist, 
make a backup of your ~/.config (/home/{username}/.config) folder and then install 
swaync, rofi-wayland, waybar and cava and then
put all the files and folders to ~/.config/ directory in your machine. it's in your home directory. restart and hope it works, tho I highly doubt it work.

I can understand your frustration, when I was new, I tried do the same, but sorry it doesn't work like that....
